name: TS Lib

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ts-lib:
        strategy:
            fail-fast: false
            matrix:
                node-version: [20.x]
                os: [ubuntu-latest, windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}

        defaults:
            run:
                working-directory: ./ts-lib

        steps:
            - uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: 0.12.0
            - run: zig build
              working-directory: ./
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: ts-lib/package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Run tests
              run: npm test
            - name: Safari Tests
              if: matrix.os == 'macos-latest'
              run: npm run test:safari
            - name: Chrome Tests
              if: always()
              run: npm run test:chrome
            - name: Firefox Tests
              if: always()
              run: npm run test:firefox
            - name: Edge Tests
              if: matrix.os != 'macos-latest'
              run: npm run test:edge
            - name: Benchmarks
              if: always()
              run: npm run bench
