name: Zig Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: 0.12.0
            - run: zig build test --summary all
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
            - run: zig fmt --check src/*.zig
