name: Zig Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: 0.14.0-dev.1710+8ee52f99c
            - run: zig build test --summary all 
              if: matrix.os == 'windows-latest' # Fuzzing is not supported on Windows yet
            - run: zig build test --fuzz --summary all 
              if: matrix.os != 'windows-latest'
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
            - run: zig fmt --check src/*.zig
